@startuml

|Gen3| Gen3
start

note
  User is in Explorer
endnote

:click login;
|Auth0| Auth0
while (new user)
  :Register
    **name**
    **email**;
  group "optional" {
    if (email in\nallowlist)
    else (no)
      stop
    endif
  }
  :Verify email;
  if (email\nverified)
  else (no)
    stop
  endif
endwhile
while (forgot password)
  :Reset Password;
endwhile
:Log in;
:redirect to\noriginal page;

|Gen3|
stop

@enduml